# Generated by Django 5.0.2 on 2024-03-02 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cont', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('id_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('id_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.rules')),
            ],
        ),
        migrations.AddField(
            model_name='tests',
            name='id_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='id_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.topic'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fname', models.CharField(max_length=128)),
                ('id_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.worker')),
                ('id_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.rules')),
            ],
        ),
        migrations.CreateModel(
            name='Progresstests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.tests')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Progresslesons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(null=True)),
                ('id_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.lesson')),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_worker', models.ImageField(null=True, upload_to='')),
                ('id_rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.rules')),
                ('id_worker_parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('id_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_system.worker')),
            ],
        ),
    ]
