# Generated by Django 5.0.2 on 2024-03-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
