# Generated by Django 5.0.2 on 2024-03-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_system', '0003_answers_answer_answers_istrue_files_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='name',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
    ]
