# Generated by Django 5.0.2 on 2024-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_system', '0005_alter_worker_id_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='id_worker',
            field=models.IntegerField(null=True),
        ),
    ]
