# Generated by Django 5.0.2 on 2024-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_system', '0006_alter_invite_id_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
